package se.lexicon;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.*;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class ArrayDemoTest {

    @Test
    @Order(2)
    @DisplayName("Find max number with positive numbers")
    void findMaxNumberWithPositiveNumbers() {
        // Scenario: A standard array of positive numbers
        int numbers[] = {1, 5, 3, 9, 2};

        // Expected max number is 9
        int expected = 9;

        // Actual max number should be generated by the implemented method
        int actual = ArrayDemo.findMaxNumber(numbers);

        // Verify the result
        assertEquals(expected, actual, "The max value should be 9.");
    }


    @Order(1)
    @Test
    @DisplayName("Find max number with negative numbers")
    void findMaxNumberWithNegativeNumbers() {
        // Scenario: An array containing only negative numbers
        int numbers[] = {-10, -5, -20, -3, -15};

        // Expected max number is -3 (largest among the negative values)
        int expected = -3;

        // Actual max number should be generated by the implemented method
        int actual = ArrayDemo.findMaxNumber(numbers);

        // Verify the result
        assertEquals(expected, actual, "The max value should be -3.");
    }

    // todo: add more test cases here as needed
}
